name: KCPP-F Linux full bin CUDA 12.1.0

on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  KCPP_CUDA: 12.1.0

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install git curl bzip2

      - name: Build
        id: make_build
        run: |
          ./koboldcpp.sh dist

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: kcpp_fks_linux_cuda_12.1.0_binary
          path: dist/
